version: '3.8'

services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80" 
    depends_on:
      - server 
    networks:
      - my_net


  db:
    image: postgres:17.2
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: work_db
    ports:
      - "5432:5432"
    networks:
      - my_net
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - my_net

  server:
    build: ./backend/ 
    container_name: server
    ports:
      - "5000:5000" 
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=work_db
    depends_on:
      - db 
    networks:
      - my_net


volumes:
  postgres_data:

networks:
  my_net:
    driver: bridge

