name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main # Запускать при создании Pull Request в ветку main

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Выгрузка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: |
          cd backend 
          npm test

      # Шаг 5: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 6: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/backend:latest ./backend

      # Шаг 7: Публикация Docker-образа
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/backend:latest