name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Deploy to server and build locally
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/laba4/frontend # Path to your project's frontend directory on the server
            git pull origin main

            # Install dependencies and build the React app ON THE SERVER
            echo "Installing frontend dependencies on server..."
            npm install
            echo "Building frontend project on server..."
            npm run build

            echo "Building Docker images..."
            docker-compose build

            echo "Stopping and removing old containers (if any)..."
            docker stop server frontend || true # Stop specific containers if they might have custom names
            docker rm server frontend || true   # Remove specific containers
            docker-compose down --remove-orphans

            echo "Starting new containers..."
            docker-compose up -d